=== tinrael/distributed-computing-labs2/lab1/data/departments.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.company.com/departments"
	xmlns:tns="http://www.company.com/departments"
	elementFormDefault="qualified">
	
	<element name="departments">
		<complexType>
			<sequence>
				<element name="department" type="tns:Department" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	
	<complexType name="Department">
		<sequence>
			<element name="employee" type="tns:Employee" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="id" use="required">
			<simpleType>
				<restriction base="ID">
					<pattern value="[d][-]([0-9])+" />
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="name" type="string" use="required" />
	</complexType>
	
	<complexType name="Employee">
		<sequence>
			<element name="forename" type="string" />
			<element name="surname" type="string" />
			<element name="salary" type="positiveInteger" />
		</sequence>
		<attribute name="id" use="required">
			<simpleType>
				<restriction base="ID">
					<pattern value="[e][-]([0-9])+" />
				</restriction>
			</simpleType>
		</attribute>
	</complexType>
</schema>

=== tinrael/distributed-computing-labs2/lab1/data/departments.xml
<?xml version="1.0" encoding="UTF-8"?>
<departments xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.company.com/departments"
	xsi:schemaLocation="http://www.company.com/departments departments.xsd">
	
	<department id="d-0" name="sales">
		<employee id="e-0">
			<forename>John</forename>
			<surname>Johnson</surname>
			<salary>1400</salary>
		</employee>
	</department>
	
	<department id="d-1" name="finance">
		<employee id="e-1">
			<forename>Jack</forename>
			<surname>Jackson</surname>
			<salary>1200</salary>
		</employee>
		
		<employee id="e-2">
			<forename>Emily</forename>
			<surname>Smith</surname>
			<salary>1500</salary>
		</employee>
	</department>
</departments>
